### ISSUE TITLE
Unexpected token error

### ISSUE THREAD

**Issue by ahughes03** [tonywagner/mlbserver#13]
Here's the error message. I tried starting the program a few times with various flags like -c and -l in an attempt to flush any caches, but I'm still getting the error after a reboot. This happened immediately after updating to 2022.03.23.

```
SyntaxError: Unexpected token r in JSON at position 1352
    at JSON.parse (<anonymous>)
    at loadFromFile (/usr/local/lib/node_modules/mlbserver/node_modules/tough-cookie-filestore/lib/filestore.js:148:32)
    at new FileCookieStore (/usr/local/lib/node_modules/mlbserver/node_modules/tough-cookie-filestore/lib/filestore.js:14:5)
    at new sessionClass (/usr/local/lib/node_modules/mlbserver/session.js:101:33)
    at Object.<anonymous> (/usr/local/lib/node_modules/mlbserver/index.js:80:15)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by ahughes03** [comment]
... and it's gone. Tried updating and manually starting (instead of via my systemd service) and it's working as expected. After an initial launch and stop, my systemd service is working as well.

Thanks!

**Comment by tonywagner** [comment]
Looks like your cookie file got malformed somehow. Next update I'll include some code to check that so the program can recover if it happens again.
